### ISSUE TITLE
Add support for the HTTP HEAD verb

### ISSUE THREAD

**Issue by henrylearn2rock** [atuttle/Taffy#13]
HTTP HEAD verb should be supported.

**Comment by JamoCA** [comment]
How is HEAD supported?  I attempted to add it based on the sample (which displays the use of GET instead of HEAD) and it doesn't seem to be working.

USE CASE: I'm attempting to use "WGET --spider" to access a list GET API endpoints (protected by IP/obfuscated useragent rules).   WGET performs a HEAD request first to determine if the URL is valid before performing the GET request.  WGET indicates that the link is valid, but doesn't like something about it... it's possible that it doesn't like the "application/json" type and is expecting "html". Is there a way to return "text/html"? (I saw a sample of that too, but it didn't work.)

Here's the code I added to the CFC endpoint:

    <cffunction name="head" taffy:verb="head" taffy:mime="text/html" access="public" output="false" hint="Required for WGET; it verifies file before performing GET request">
        <cfreturn noData().withStatus(200) />
    </cffunction>
