### ISSUE TITLE
Support documentation of complex types

### ISSUE THREAD

**Issue by guillaume-boivin** [atuttle/Taffy#246]
Currently, if you have an argument of an operation for one of your resource that is a a structure of data, you have no way of documenting the details of this structure. From what I understand you need to put struct as the type of the argument and the user of your webservice typically needs to guess what needs to go there (or you write a pretty long hint message for that struct argument).

It would be great if we could document this via a cfc and some metadata attributes on the arguments themselves. I was thinking about using a cfc with properties representing the data structure and putting this cfc's type in the type attribute of the argument. That way we could update the doc, and the live example with the data structure and the hints.

I'm willing to do this change if you think it's worth it.

**Comment by ryanguill** [comment]
Can you give a concrete example of a resource that fits this use case? In the case of a JSON body for example, taffy will map the keys of the JSON object into individual arguments in the request - or are you talking about a level deeper than that?

**Comment by guillaume-boivin** [comment]
simple example json for a property : 
{
    "propertyName": "house",
    "owner": {
        "firstName": "john",
        "lastName": "smith"
    }
}

Yes a level or more deeper actually.

**Comment by atuttle** [comment]
You can also put hint attributes on each argument; does that help?

**Comment by guillaume-boivin** [comment]
Not really helpful for arguments representing complex types in my opinion. Because you will have to explain the complex data structure in one big chunk of text. It's definitely do-able but I don't think is a viable solution.

**Comment by guillaume-boivin** [comment]
Proof of concept :
![image](https://cloud.githubusercontent.com/assets/10443125/5694316/1d0dad68-991d-11e4-8992-b107c7995538.png)

**Comment by atuttle** [comment]
I have to say that on the face of it im not in love with the idea. The idea of using additional classes to define incoming data reminds me of SOAP. Further, I think that while this may scale fine in data depth it would be a bit of a nightmare to scale in width. If you have 50 properties each with one or two sub-keys, creating and maintaining objects simply to define the documentation sounds less than fun.

I'm not opposed to some solution to this problem I just don't think this one is it yet.

**Comment by guillaume-boivin** [comment]
You are going to have to add structured info in a way or the other to solve this problem. Be it a cfc, a xml or another item that will describe the incoming structure. I'm not particularily fixed with one yet, do you have a preference ?

**Comment by atuttle** [comment]
I see your point, but I still think it's kind of a niche case. I don't think you're wrong, I just don't think it's something that the code needs to support for the ~5% of users that may eventually make use of it, especially considering how much complexity it will add to the dashboard and documentation generation functionality.

If you feel strongly that it's something important for the framework to have, maybe we should take it to the mailing list (I doubt many users pay attention to every issue here) and see if we can rally up more support for the idea. Perhaps I don't see the utility in it because I don't see myself using it. If many people agree with you, I could be convinced.

**Comment by guillaume-boivin** [comment]
Deal. Let's find out the support it's going to get (or not) ! ;)

Gonna write that to the mailing list this week when I have time.

**Comment by guillaume-boivin** [comment]
So, I'm not getting support from people in the mailing list. Seems like the only person that needs this is me. 

One side note about this is that it could have been great to link data validation to the cfc's describing incoming data, that way it would be a pretty all around solution, as you are going to have to validate data anyways.

**Comment by atuttle** [comment]
Something that I would be in favor of would be some sort of pluggable system within Taffy. I've only just begun to think about it, but instead of building in something like what you're asking for, if there were instead some sort of general solution for creating your own plugins, I'd be in favor of that.

**Comment by rcastagno** [comment]
This should really be implemented IMHO, it would allow to rationalize parameters in a more structured way, and reduce duplication.
It's the way OpenAPI/Swagger does API specification.
