### ISSUE TITLE
Taffy endpoint URL rewrite

### ISSUE THREAD

**Issue by pelfed** [atuttle/Taffy#250]
Using Coldfusion 8, windows 2008 server, I'm trying to get the endpoints working without having to do:

http://api.wesbite.com/index.cfm?endpoint=xyz

I have tried http://api.wesbite.com/index.cfm/xyz - as this is supposed to work out of the box?  but I get a 404.

We are on IIS7 and setup web.config as per instructions (which are slightly wrong as rule needs a name) as follows:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<system.webServer>
		<rewrite>
			<rules>
				<rule name="api">
					<match url="^/([.*])$" />
					<action type="Rewrite" url="index.cfm/{R:1}" />
				</rule>
			</rules>
		</rewrite>
	</system.webServer>
</configuration>
```

I have remove the 'api' bit as i want the url endpoint to be like:

api.website.com/xyz

But still get a 404. 

Can anyone help?  many thanks in advance

**Comment by atuttle** [comment]
Yes, `/index.cfm/xyz` is supposed to work out of the box, especially on Windows & IIS. Elsewhere it can be a little more tricky.

Let's ignore the URL rewriting for now (you can disable it if you want, or not, shouldn't make a difference), because if you can't get `/index.cfm/xyz` to work then `/xyz` isn't going to work either because it makes IIS treat the latter as if it were the former.

You say you're getting a 404: is that an IIS 404 (the blue-ish screen) or a Taffy 404 (which will be an empty screen but may have some useful information in the headers)?

What happens when you try browsing to http://api.website.com/ ? You should see the Taffy dashboard and it may give you some hints on what needs to be done to move things along.

**Comment by pelfed** [comment]
I managed to get it all working in the end.  I had to amend the web.config to the following:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="api" stopProcessing="true">
                    <match url="(.*)/(.*)$" ignoreCase="false" />
                    <action type="Rewrite" url="/index.cfm?endpoint=/{R:0}" appendQueryString="true" />
                </rule>
            </rules>
        </rewrite>
        <httpErrors existingResponse="PassThrough" />
    </system.webServer>
</configuration>
```

**Comment by atuttle** [comment]
Cool, glad you got it worked out. It seems like the IIS config stuff keeps changing, so we just have to keep updating the docs. I've updated the wiki page to take your changes into account: https://github.com/atuttle/Taffy/wiki/URL-Rewrite-Rule-Examples#iis7-webconfig

**Comment by JamoCA** [comment]
I had to use the following URL Rewrite. I'm not sure if it was due to some other rules, but the default sample from the wiki (with `{R:0}`) was returning `?endpoint=api/endPointName` instead of `?endpoint=endPointName`

    <rule name="TaffyAPI" stopProcessing="true">					
      <match url="api/(.+.*)$" ignoreCase="true" />
        <conditions>
          <add input="{PATH_INFO}" pattern="^.*/index.cfm.*$" negate="true" />
        </conditions>
      <action type="Rewrite" url="/api/index.cfm?endpoint=/{R:1}" appendQueryString="true" />
    </rule>
