### ISSUE TITLE
Issue with rewriting and errors

### ISSUE THREAD

**Issue by edthetechie** [atuttle/Taffy#274]
I successfully got rewriting working in IIS 7 using the provided webconfig, but now that it's working I'm seeing some odd behaviour. A page returning a 200 works fine:
http://demoapi.shapingtomorrow.com/test
But when I try to access my authenticate endpoint which should return a 401 "not authorised" http header all I get is a blank page:
http://demoapi.shapingtomorrow.com/authenticate
When I turn off the rewriting it works as expected. Is this a bug or something I'm doing wrong?

**Comment by atuttle** [comment]
In IIS, you need to, at least at the site-wide level (if not more broadly),
enable "detailed errors"

[image: Inline image 1]

Adam

**Comment by edthetechie** [comment]
I think that was done on the server already, the attached image seems to indicate so. I didn't see the inline image you put in your reply though so I'm not sure I'm looking at the right settings
![Uploading 2015-05-15_1703.png…]()

**Comment by edthetechie** [comment]
Didn't mean to close it! Misclick, sorry!

**Comment by atuttle** [comment]
Heh, looks like your image didn't finish uploading or something...

I think the issue is just that you're expecting something based on prior experience, but while you're getting the desired result, it doesn't look like what you assumed it would. If you inspect the request, you'll see that it does return 405:

![image](https://cloud.githubusercontent.com/assets/46990/7656860/00233cbc-faf3-11e4-96a9-05bb5b1e14b8.png)

![image](https://cloud.githubusercontent.com/assets/46990/7656864/09bfce0c-faf3-11e4-9367-d156aec9ef18.png)

**Comment by edthetechie** [comment]
Duh! Thanks! You're right about my expectations. This is my first API so very much on a learning curve. Note to self: use the dev tools next time!
Thanks very much for your help with this. I'll use the forum next time as well instead of posting here.
