### ISSUE TITLE
{var} URI Tokens not working in tomcat 8

### ISSUE THREAD

**Issue by actsone** [atuttle/Taffy#284]
Hello

URI tokens (parameters) not working in tomcat 8.
It is a very strange phenomenon.

If I using URL tokens (parameter) and query from db by GET.
- if data existed, return data using the "representationOf(response).withStatus(200)"
  => result : not working (empty result and 404 error)
- if data not existed, return data using the "representationOf(response).withStatus(200)"
  => result : show the empty result ([]).
- if I sent parameter by url parameter (?id=value),
  => result : show the real data

If I change GET to POST. 
 - can't using the URL tokens (why?), only can send by "Request Body" (It's maybe form submit).
 - If I remove the URL tokens, and send by "request body"
  => result : show the real data, but I want using the "URL token"

What's problem and how solve it?

**Comment by actsone** [comment]
I found the reason.

If I send URL token that included "." notation, then error happen. (for example : email address)

How to solve it?

**Comment by atuttle** [comment]
Email address as the final token has been a long-standing known issue with Taffy. The trouble is that we support `.json`-in-the-uri style return-type specification (e.g. `/foo/bar.json`) so it is difficult, if not impossible (when the email address is the LAST thing in the URI) to know when the TLD of the email address is part of the email address, or is a requested return type.

Here are a few potential work-arounds:

- Don't put the email address at the end of your URI: Use `/users/{email}/profile` instead of `/users/{email}`
- Require the return type specification if email will be last, as in: `/users/foo@bar.com.xml`

**Comment by actsone** [comment]
Ok. I see, I will try it.

Thanks.
