### ISSUE TITLE
Using PUT instead of POST for file uploads

### ISSUE THREAD

**Issue by gugahoi** [atuttle/Taffy#306]
I would like to use the `PUT` verb instead of `POST` however the same code that works for `POST` is not working for `PUT` - it does not have the request payload anymore and I get an exception saying `audioFile` does not contain a file.

````
	function post(required numeric tenantId, required numeric surveyId, audioFile){
		try {
			savePath = expandPath("/prompts/" & tenantId & '/' & surveyId & '/');

			if(!directoryExists(savePath)){
				directoryCreate(savePath);
			}

			uploadResult = fileUpload(savePath, "audioFile", "audio/wav,audio/x-wav", "MakeUnique");
			return this.get(tenantId=tenantId, surveyId=surveyId);
		} catch(any e){
			return rep( e ).withStatus('500', e.getMessage());
		}
	}
````

Is it possible to use `PUT` at all?

**Comment by atuttle** [comment]
You know, I never thought to try. I bet that this is a limitation of ColdFusion. Its implementation of HTTP has several holes that they just ignored because it didn't fit the most common use-cases.

You could try making the request a POST but setting the header `X-HTTP-METHOD-OVERRIDE: PUT` so that Taffy will use your PUT handler to process it.

**Comment by gugahoi** [comment]
This is an interesting approach. For my purposes I just moved to a POST request to save some time.
