### ISSUE TITLE
How to show a different Name for a resource in Taffy Dashboard

### ISSUE THREAD

**Issue by saazzou** [atuttle/Taffy#316]
Hello,

I have a cfc file in a resource subfolder, example : 

/resources/foo/bar.cfc

In the dashboard i got the name : foobar, is there a way to change it to something like : superfoovsbarman ?  

Thanks,

**Comment by atuttle** [comment]
Not currently possible, thought I don't see why we couldn't add a component attribute for it. Perhaps `component taffy:displayName="Foos" { ... }`

**Comment by y2kiah** [comment]
With the recent introduction of the taffy:docs namespace for taffy:docs:hide, this could be added as taffy:docs:name. Similarly, we could introduce taffy:dashboard:hide and taffy:dashboard:name, since I believe there is a use case for have separately configurable docs and dashboard. Components also have the built-in displayname attribute which could be respected in the absence of taffy:docs:name, and would override the auto-generated taffy name for display purposes.

**Comment by atuttle** [comment]
I've seen the built in `displayName` attribute cause problems in the past so I am hesitant to use it. I'm all for a `taffy:docs:name` and `taffy:dashboard:(name|hide)` options, though! 👍
