### ISSUE TITLE
Custom serializer per method

### ISSUE THREAD

**Issue by Thom1729** [atuttle/Taffy#341]
I've written a function that takes in a Coldfusion value and a JSON schema and converts the value to JSON conforming to that schema. For instance, the value `"0123"` and the schema `{ "type": "string" }` will produce the JSON output `"0123"` (rather than `123`).

The trouble is, I can't figure out how to get the thing wired up in Taffy. I could set a global custom serializer, but that wouldn't have access to the method metadata where I'd like to put the schema URIs. And there doesn't seem to be any way of setting a custom serializer for a single method.

**Comment by atuttle** [comment]
I don't think even having a custom serializer per `return rep()` call would solve this. The serializer's job is to take the data and convert that into the desired return format. It isn't given any information about the request.

I am personally opposed to JSON schemas. Why make it more like XML? JSON is not XML for a reason. Anyway... If you insist on using this approach, my recommendation would be to make use of the request scope and a global serializer. Your resources could set the appropriate schema into request scope and then the serializer can reference it during serialization.

A looooong time ago, Taffy supported an additional argument to the `representationOf()` method to override the default serializer, but it turned out that nobody used it because nobody needed it. So it was removed in favor of simplification. (But as I said, I don't think that adding it back would solve your problem.)

**Comment by Thom1729** [comment]
I've solved the problem by overriding the `getRepInstance` method. I hadn't realized that the method attributes were accessible from the `Request`scope. Because they are, I check for the `returnSchema` attribute in `getRepInstance` and use it to construct the appropriate serializer.

I don't see what XML has to do with anything. We work with a variety of complex data, and we have to validate it on the way in. JSON schema are an excellent way of strictly defining a data format. They're easy for another developer to read and edit. If a typo or a careless developer produces invalid input, it will fail to validate against the schema and the bug will be caught immediately. And as an added bonus, having a defined schema means that we can automatically circumvent ColdFusion's serialization quirks; for instance, a string of digits will never be incorrectly serialized as a number. (I was under the impression that this sort of thing was a common complaint about ColdFusion.)

Of course, your mileage may vary. I work on very large, complex systems with two dozen other developers. If the software were smaller and more temporary, and fewer people had to work on it, then perhaps we could get away with not declaring our API inputs and outputs.

In any case, the issue is moot because the premise (that the method metadata was not easily accessible from remote parts of the application) was misinformed. There is a reasonable solution with existing functionality.
