### ISSUE TITLE
Support for `Access-Control-Expose-Headers`

### ISSUE THREAD

**Issue by timmixell** [atuttle/Taffy#377]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

I first happened across this one when working with Taffy's Etag feature in my Javascript client implementation. Custom headers added using `withHeaders` suffer a similar problem.

I would propose that if Etag is enabled and/or any custom headers are present, to include those keys inside an `Access-Control-Expose-Headers` response header within `onRequest` (after the Etag check)

**Comment by atuttle** [comment]
Sounds good to me! Since we offer developers the ability to add custom response headers from within resources, we should also have a way to list them here too. I'm open to suggestions for the implementation of all of the above. In general I prefer metadata over a big blob of config, but sometimes a BBOC is the best solution.
